### ISSUE TITLE
[Feature]: It seems that comfyui-reactor-node, ComfyUI_LayerStyle, and comfyui_controlnet_aux, the three plugins, cannot work together perfectly no matter what. The issue lies in the opencv dependency package.

### ISSUE THREAD

**Issue by wibur0620** [Gourieff/comfyui-reactor-node#231] opened 2024-02-23 00:07 UTC
### Feature description

No matter how I adjust the version of the opencv dependency package, the three plugins, comfyui-reactor-node, ComfyUI_LayerStyle, and comfyui_controlnet_aux, cannot work together simultaneously. For more details, please refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5.

I hope that you three authors can communicate and work together to solve this issue.

**Comment by chflame163** [comment] 2024-02-23 08:27
I have identified the cause of the problem on [here](https://github.com/chflame163/ComfyUI_LayerStyle/issues/5#issuecomment-1960865706)

**Comment by wibur0620** [comment] 2024-02-23 11:39
> > > After importing ComfyUI_LayerStyle, this time I closed comfyui-reactor-node and restarted comfyui. Finally, everything is working fine now, which is quite perplexing. I really need all three plugins, but now I have to give up starting one of them in order to run smoothly. [comfyui.txt](https://github.com/chflame163/ComfyUI_LayerStyle/files/14380650/comfyui.txt)导入ComfyUI_LayerStyle后，这次我关闭了 comfyui-reactor-node 并重新启动了 comfyui。最后，现在一切正常，这非常令人困惑。我真的需要所有三个插件，但现在我必须放弃启动其中一个才能顺利运行。comfyui.txt
> > 
> > 
> > As you said, the comfyui-reactor-node has done some processing on sys.modules. I checked his code and found the issue at line 32 of comfyui-reactor-node/__ init__. py.正如您所说，comfyui-reactor-node 对 sys.modules 进行了一些处理。我检查了他的代码，并在 comfyui-reactor-node/__ init__ 的第 32 行发现了问题。py。
> > Modifying this line to将此行修改为
> > `if module not in original_modules and not module.startswith("google.protobuf") and not module.startswith("onnx") and not module.startswith("cv2"):`
> > can solve the problem.可以解决问题。
> > <img alt="20240223153613" width="1160" src="https://private-user-images.githubusercontent.com/130118553/307252202-43c86c8b-3e75-4cdc-9339-17db0fe38eb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODY4NjYsIm5iZiI6MTcwODY4NjU2NiwicGF0aCI6Ii8xMzAxMTg1NTMvMzA3MjUyMjAyLTQzYzg2YzhiLTNlNzUtNGNkYy05MzM5LTE3ZGIwZmUzOGViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMTA5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGY5OWI1ZmIwYmU4ODVkZTU4MzFhZGQxODk1NDRmN2Y2YzQ5OTRkNDNkNjNmYjgxMDVlZDhkNzI2YTkyZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2Th1X3dmHBrcxn2Jz6l7GRbzFe6aoCKbL-Xz4QUWP0s"> <img alt="20240223154454" width="315" src="https://private-user-images.githubusercontent.com/130118553/307252277-16e8948e-cef5-4e1a-9c3a-d07e319e13ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODY4NjYsIm5iZiI6MTcwODY4NjU2NiwicGF0aCI6Ii8xMzAxMTg1NTMvMzA3MjUyMjc3LTE2ZTg5NDhlLWNlZjUtNGUxYS05YzNhLWQwN2UzMTllMTNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMTA5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWQxNzYxNDc5YzY3ZjJmYjk1OWUyNzYyNjkxMTE1YjQ2NTljYjUyNDIzNjQwNGU2ODQ3ZmYwNWJmNmMxODY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eSwMGu2_gRwKtyQfFg7GHXO25LZLzcrE3112cIRcgfA">
> 
> Thank you very much for your help, they are now working perfectly after I made the changes the way you did, but I'm still a bit worried. If the next update will the same problem occur again [ComfUI.txt](https://github.com/chflame163/ComfyUI_LayerStyle/files/14384560/ComfUI.txt) Uploading Windows PowerShell.txt…

This require that plugin author to submit code modifications.

_Originally posted by @chflame163 in https://github.com/chflame163/ComfyUI_LayerStyle/issues/5#issuecomment-1961167895_

**Comment by Gourieff** [comment] 2024-02-23 16:01
Ok, will be fixed with the next update
Thanks for spotting

**Closed** 2024-02-27 07:13 UTC
Labels: enhancement, ✔ done
